CREATE TABLE "users" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar(100) UNIQUE NOT NULL,
                         "email" varchar(255) UNIQUE NOT NULL,
                         "password_hash" varchar(255) NOT NULL,
                         "role" varchar(50) NOT NULL,
                         "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "categories" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" varchar(100) NOT NULL,
                              "slug" varchar(150) UNIQUE NOT NULL,
                              "description" text
);

CREATE TABLE "articles" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "title" varchar(255) NOT NULL,
                            "slug" varchar(255) UNIQUE NOT NULL,
                            "summary" text,
                            "content" text NOT NULL,
                            "status" varchar(50) NOT NULL DEFAULT 'DRAFT',
                            "cover_image_url" varchar(500),
                            "category_id" int NOT NULL,
                            "created_by" int NOT NULL,
                            "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                            "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                            "published_at" timestamp
);

ALTER TABLE "articles" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "articles" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;